version: '3.2'

services:
  gateway:
    build: .
    container_name: gateway
    volumes:
      - ./:/app
    command: >
      bash -c "pipenv run alembic upgrade head
      && pipenv run python . "
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
